const FETCH_START = '[menu]/FETCH_START';

const FETCH_SUCCESS_MENU_LIST = '[menu]/FETCH_SUCCESS_MENU_LIST';

const FETCH_SUCCESS_MENU_CATEGORIES = '[menu]/FETCH_SUCCESS_MENU_CATEGORIES';

const FETCH_ERROR = '[menu]/FETCH_ERROR';

export default {
  FETCH_START,
  FETCH_ERROR,
  FETCH_SUCCESS_MENU_LIST,
  FETCH_SUCCESS_MENU_CATEGORIES,
};
